name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: prevent aclocal.m4 rebuilding
      run: touch aclocal.m4
    - name: prevent Makefile.in rebuilding
      run: touch Makefile.in
    - name: prevent test/Makefile.in rebuilding
      run: touch test/Makefile.in
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
